name: remote ssh command
on:   
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:    
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        node-version: [18]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set Up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --force

      - name: Build
        run: yarn build
    
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd orineko-frontend &&
            pm2 stop orineko-frontend &&
            git fetch origin main &&
            git reset --hard origin/main &&
            yarn install --force &&
            yarn build &&
            pm2 restart orineko-frontend
